services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Anubit\LighthouseInsight\:
    resource: '../Classes/*'

  Anubit\LighthouseInsight\Controller\PageSpeedController:
    public: true
